### ISSUE TITLE
max_price, cb_url and allow_dot does not exist in type DigiflazzTransactionProps

### ISSUE THREAD

**Issue by An-Ace** [karyanayandi/digiflazz-sdk#1]
I know this may be a small detail, but I think it will be very helpful.
**max_price, cb_url and allow_dot does not exist in type DigiflazzTransactionProps**

**Comment by karyanayandi** [comment]
> I know this may be a small detail, but I think it will be very helpful. **max_price, cb_url and allow_dot does not exist in type DigiflazzTransactionProps**

thanks for your feedback

Fixed with commit 0a9e5ce767e53c0e1b5ca4af2abb6928293baff4
